### ISSUE TITLE
Wallet unreachable even with app active

### ISSUE THREAD

**Issue by shnoah641** [i1skn/ironbelly#123]
I have left the wallet running for iron belly and have received nothing. I even tried checking the box to keep the app open to receive and still nothing. The website https://grinchck.uber.space/ tells me that my wallet is unreachable. 

Wallet address: grin1ntwtak32r040xjepqe7e7mw54pp3mrruzmsjz74hn6u5fcxc0f5q20sm4t

![Screenshot_20230630_135725_Brave](https://github.com/i1skn/ironbelly/assets/72530034/26fa0121-ab60-4e04-81be-8e4a1838be31)

**Comment by i1skn** [comment]
Just to confirm, you're checking reachability of Ironbelly by opening https://grinchck.uber.space/ on the same phone, where Ironbelly is running in background? If yes - this would not work, Ironbelly must opened and in foreground, so please use another device to check its reachability. If you're doing it on another phone - please try to use different network/vpn as Grin is using TOR under the hood to transact. If you do not have access to TOR - you would not be able to transact via addresses.

**Comment by shnoah641** [comment]
I do get tor and I get peers just when I try and check the address if it is
reachable when on the iron belly application it says not reachable even if
it is in the foreground it does that. Or even if I do check the address on
a different phone it still says not reachable.

**Comment by shnoah641** [comment]
Ok I just changed that setting. It's showing wallet as online now I'll keep
you updated on whether I receive a transaction or not.

**Comment by shnoah641** [comment]
Yeah no it's still not working even after that setting and restarting the
app

**Comment by shnoah641** [comment]
I even have the app set for unrestricted background use too

**Comment by i1skn** [comment]
So, does https://grinchck.uber.space/ say the wallet is available?

**Comment by shnoah641** [comment]
It does when I have the wallet open but if I try the lock in background it
does for maybe 10 minutes and then back offline again

**Comment by shnoah641** [comment]
This is also on Android 13 if that helps any

**Comment by i1skn** [comment]
> It does when I have the wallet open but if I try the lock in background it
does for maybe 10 minutes and then back offline again

When you background the app -> address becomes inaccessible. I'm not sure about 10 minutes after, probably some caching is going on an https://grinchck.uber.space/.

Generally, if the wallet is accessbile on https://grinchck.uber.space/ - you should be able to transact on it. But DO NOT background the app or allow the phone to go sleeping if you're awaiting a transaction.

**Comment by shnoah641** [comment]
New update my wallet is not reachable even on screen with ironbelly running
and unlocked now

**Comment by i1skn** [comment]
It's seems like that there is indeed a problem, but it's rather hard to actually figure out the reason, as it's connected with TOR connection... Unfortunately, I do not have capacity right now to go deeper into this. Considering, that you're on Android, please try Grin++ wallet and see if it works for you. Closing this one.

**Comment by shnoah641** [comment]
I just tried the grin++ and I had it crash about 3/4 of the way syncing at
about 25% of the way and then it resets back to 2/4 again.
