### ISSUE TITLE
Implement Share Extension

### ISSUE THREAD

**Issue by i1skn** [i1skn/ironbelly#27]
As a part of the project `Share Extension` needs to be implemented and "Copy to Ironbelly" should be renamed to "Ironbelly".

**Comment by irshadpc** [comment]
@i1skn , I prefer "Copy to Ironbelly".

**Comment by irshadpc** [comment]
@i1skn why this issue still opened

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by i1skn** [comment]
@irshadpc cause this is not implemented yet. I've updated the description.
