### ISSUE TITLE
Additional protection for the Paper Key screen

### ISSUE THREAD

**Issue by i1skn** [i1skn/ironbelly#33]
from Calin Pasat:
> Wanted to suggest maybe being required additionaly to scan Face 
> ID/require to type password when accesing the Paper Key in Settings as 
> an added security measure in case somebody malicious grabs your phone 
> after you first initial unlock of the wallet!

**Comment by irshadpc** [comment]
@i1skn As per the standards ( like [Trust wallet](https://apps.apple.com/us/app/trust-crypto-bitcoin-wallet/id1288339409), [Natrium](https://apps.apple.com/no/app/natrium/id1451425707) ) when the user needs to know their wallet private key/seed they need to re-enter the passcode(password,touch-id, etc.).

**Comment by irshadpc** [comment]
@i1skn This is a high priority feature we need to implement.

**Comment by i1skn** [comment]
Been implemented in 4.3.0
