### ISSUE TITLE
Add ability to copy-paste TX slates, instead of sharing files

### ISSUE THREAD

**Issue by phreaknik** [i1skn/ironbelly#47]
File sharing seems finicky on mobile devices. Furthermore, some chat apps (in particular some privacy apps) make file sharing even more difficult. It would be very nice to be able to copy/paste TX slates to/from IronBelly.

For robustness slates could be base64 encoded with a checksum (to protect against typos / paste errors)

**Comment by i1skn** [comment]
Was implemented in version 4.0.0
