### ISSUE TITLE
Make transaction info fields non-editable 

### ISSUE THREAD

**Issue by milkyklim** [i1skn/ironbelly#63]
_Amount_ and _Time_ fields should not be editable/clickable. 

At the moment, I can click these fields and get the keyboard (see screenshot).

![IMG_82C2F2AB1247-1](https://user-images.githubusercontent.com/10698619/75669759-e0c59780-5c7b-11ea-9ff0-2d7b2946990f.jpeg)

**Comment by i1skn** [comment]
@milkyklim Thanks for taking your time and reporting it!

**Comment by i1skn** [comment]
Fixed in `v3.1.0` (soon will be released on Android as well)
