### ISSUE TITLE
Cannot import text file becasue error message

### ISSUE THREAD

**Issue by le-dawg** [i1skn/ironbelly#65]
I try to import my transaction file on Android 10 OnePlus 6 but I see that the screen shows an error message with red background for about...80ms and then it is gone. I cannot read. Screen recording is not possible because deactivated. Help debug. WTF.

**Comment by i1skn** [comment]
Hi, without the message it is very hard to identify the problem. If none of the methods you've mentioned worked, can you try to capture the screen from another phone?

**Comment by le-dawg** [comment]
It is too fast, barely noticeable. I came up with 80ms because I used to do attention research in the past and have a feeling for how fast it was. 

The only way is to change the code to remove error messages after a minimum timeout.

Sent by Mailwise – Your emails, with style.:)
    

-------- Original Message --------

**Comment by i1skn** [comment]
The error message should be present for 2 seconds, if it disappears faster - it's a bug by its own. But even if it is disappears almost immediately and your 80ms is correct you still should be able to catch it with another phone taking video (assuming that a phone takes video around 24+ fps it should be able to capture things > 40ms).

**Comment by le-dawg** [comment]
I will take care of it next time I need to receive grin.

Sent by Mailwise – Your emails, with style.:)
    

-------- Original Message --------
