### ISSUE TITLE
iOS File Share

### ISSUE THREAD

**Issue by hrdwdmrbl** [i1skn/ironbelly#68]
Every time I try to share the file with IronBelly it says "ENOENT: no such file or directory, open '/private/var/mobile/Containers/Shared/AppGroup/...".
File was created with Grin++

**Comment by i1skn** [comment]
What phone do you have, which version of OS?

**Comment by hrdwdmrbl** [comment]
iOS: 13.6.1
IronBelly: 3.1.0 build 31

**Comment by i1skn** [comment]
Can you reproduce it using version 4.0.0?
