### ISSUE TITLE
Add `Send bug report` to the app

### ISSUE THREAD

**Issue by i1skn** [i1skn/ironbelly#9]
Currently, when users report an issue it's very hard to guess why this happens because we do not have any metadata about the state of the app when the bug happens. We need some sort of reporting system, which gathers the redux state of the app, current `wallet_data` directory, list of all redux actions from the moment of the app launch and probably a screenshot or ability to add one manually by the user. 
We also need a tool, which can push this data quickly to dev environment, so we can reproduce the bug ASAP.

**Comment by akatasonov** [comment]
Hmm, the app seems using BugSnag, which is a commercial error/crash reporting service. Are there any problems with it? @i1skn

**Comment by i1skn** [comment]
@akatasonov I would say it's a first step, because it is only catches the errors. 
There is now way currently to report wrong behaviour if error did not happen.

**Comment by i1skn** [comment]
Closing this one if favor of https://github.com/i1skn/ironbelly/issues/71
